### ISSUE TITLE
Bug when loading a save/autosave while Teleport to station window is open

### ISSUE THREAD

**Issue by RusselRaZe** [tommasodargenio/syd-teleport-to-train-station#2]
Steps:
1) Open the "Teleport to Train Station" window.
2) Save game (or wait for autosave)
3) Exit game
4) Load save file

When you load the save file, the "Teleport for Train Station" window will still be there, but you cannot close it or use it. Attempting to click on the search button will cause a crash, shown here.
![factorio_2020_12_15154531](https://user-images.githubusercontent.com/73858455/102270902-95b80080-3eec-11eb-842c-6b3976a79c4f.png)

**Comment by tommasodargenio** [comment]
Hi there,

thanks for reporting the issue and providing all the details. I believe I've found the bug and fixed it. I've uploaded the new version here and on the mod portal. I'd appreciate if you can test it and let me know if it works so I can close the issue. 

Thanks! Stay safe!

**Comment by tommasodargenio** [comment]
Solved.
